/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Edit;

import GUI.ContainerPanel;
import GUI.Simulation.SimulationCanvas;
import java.awt.Container;
import java.awt.Frame;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Néstor A. Bermúdez < nestor.bermudezs@gmail.com >
 */
public class EditionDialog extends javax.swing.JDialog {

    Editable editableElement;
    Vector<EditInfo> editInfos;
    SimulationCanvas simulationCanvasElement;

    public void setSimulationCanvasElement(SimulationCanvas simulationCanvasElement) {
        this.simulationCanvasElement = simulationCanvasElement;
    }
    /**
     * Creates new form EditionDialog
     */
    public EditionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public EditionDialog(Editable editableElement, Frame owner, boolean modal) {
        super(owner, modal);
        setTitle("Edit component");
        initComponents();
        
        mainPanel.setLayout(new EditionLayout());
        
        this.editableElement = editableElement;
        editInfos = new Vector<EditInfo>(10);
        
        int index = 0;
        EditInfo temporalEditInfo;
        while ((temporalEditInfo = editableElement.getEditInfo(index)) != null) {
            temporalEditInfo.setEditionDialog(this);
            editInfos.add(temporalEditInfo);
            index++;
        }
        
        setLocation((owner.getWidth() - getWidth())/2, 
                (owner.getHeight() - getHeight())/2);
        
        processEditInfos(editInfos);
        
    }
    
    private void processEditInfos(Vector<EditInfo> infos) {
        for (EditInfo editInfo : infos) {
            for (JComponent component : editInfo.components) {
                component.setVisible(true);
                mainPanel.add(component);
            }
        }
    }
    
    private boolean saveLogic() {
        boolean accept = true;
        for (int i = 0; i < editInfos.size(); i++) {
            EditInfo info = editInfos.elementAt(i);
            InputTypeHandler input = info.getInputTypeHandler();
            boolean valid = true;
            if(input != null)
                valid = input.isCurrentValueValid;
            else if(input == null){
                for (JComponent component : info.components) {
                    if (component instanceof JTextField) {
                        info.value = ((JTextField)component).getText();
                        if (!info.accepts(info.value))
                            valid = false;
                        break;
                    }else if(component instanceof JCheckBox){
                        info.value = ((JCheckBox)component).isSelected() ? "1" : "0";
                        break;
                    }else if(component instanceof JSpinner){
                        info.value = ((JSpinner)component).getValue().toString();
                        break;
                    }
                }
            }
            if (valid) {
                editableElement.setEditValue(i, info);                 
            } else {
                String error = "not valid values";
                if(input != null)
                    error = input.getErrorMessage();;
                                    
                errormsg.setText(error);
                accept = false;
                break;
            }
        }
        return accept;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cancelMenu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        errormsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(274, 212));
        setResizable(false);

        mainPanel.setMaximumSize(new java.awt.Dimension(274, 163));
        mainPanel.setMinimumSize(new java.awt.Dimension(274, 163));
        mainPanel.setPreferredSize(new java.awt.Dimension(274, 163));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancelMenu.setText("Cancel");
        cancelMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMenuActionPerformed(evt);
            }
        });

        errormsg.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errormsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelMenu)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errormsg, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(cancelMenu))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (saveLogic()) {
            Container parent = getParent();
            if(this.simulationCanvasElement != null)
                this.simulationCanvasElement.prepareRunWithoutAnalysis();
            else{
                parent.repaint();
            }
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMenuActionPerformed
        dispose();
    }//GEN-LAST:event_cancelMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditionDialog dialog = new EditionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelMenu;
    private javax.swing.JLabel errormsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    void setErrorMessage(String errorMessage) {
        this.errormsg.setText(errorMessage);
    }
}
