/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataStructures.ModuleLoadingError;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author Franklin
 */
public class ErrorLoadedModules extends javax.swing.JFrame {

    Map<String, String> detailsByModuleName;
    /**
     * Creates new form ErrorLoadedModules
     */
    public ErrorLoadedModules(List<ModuleLoadingError> modulesError) {
        initComponents();
        this.detailsByModuleName = new HashMap<String, String>();
        this.modulesList.setModel(new DefaultListModel());
        this.modulesList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                setAreaDetails(modulesList.getSelectedValue().toString());
            }
        });
        this.initializeModulesErrors(modulesError);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        modulesList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtModuleDetail = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loading Modules");

        modulesList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        modulesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(modulesList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel1.setText("The following modules couldn't being loaded.");

        txtModuleDetail.setEditable(false);
        txtModuleDetail.setColumns(20);
        txtModuleDetail.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtModuleDetail.setRows(5);
        jScrollPane2.setViewportView(txtModuleDetail);

        jLabel2.setText("Click one module file to view details:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 90, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList modulesList;
    private javax.swing.JTextArea txtModuleDetail;
    // End of variables declaration//GEN-END:variables

    private void initializeModulesErrors(List<ModuleLoadingError> modulesError) {
        for(ModuleLoadingError errorModule : modulesError){
            String moduleName = errorModule.getModuleName();
            ((DefaultListModel)this.modulesList.getModel()).addElement(moduleName);
            String textDetail = this.composeTextDetail(errorModule.getMainMessage(), errorModule.getErrorsDetailList());
            this.detailsByModuleName.put(moduleName, textDetail);
        }
    }
    
    private void setAreaDetails(String moduleName) {
        if(!this.detailsByModuleName.containsKey(moduleName))
            return;
        
        this.txtModuleDetail.setText(this.detailsByModuleName.get(moduleName));
    }

    private String composeTextDetail(String mainMessage, List<String> errorsDetailList) {
        StringBuilder content = new StringBuilder(mainMessage).append("\n\n");
        for(String error : errorsDetailList){
            content.append(error).append("\n\n");
        }
        return content.toString();
    }
}
