/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataStructures.Loader;
import GUI.Design.DesignWindow;
import Simulation.Configuration;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author Néstor A. Bermúdez < nestor.bermudezs@gmail.com >
 */
public class SettingsEditor extends javax.swing.JInternalFrame {

    MainWindow parent;
    /**
     * Creates new form SettingsEditor
     */
    public SettingsEditor(MainWindow parent) {
        initComponents();
        
        File mods = new File(Configuration.MODULES_DIRECTORY_PATH);
        File metas = new File(Configuration.MODULE_METADATA_DIRECTORY_PATH);
        
        this.compileOnSaveCB.setSelected(Configuration.COMPILE_ON_SAVE);
        this.debugModeCB.setSelected(Configuration.DEBUG_MODE);
        this.shModName.setSelected(Configuration.USE_CUSTOM_MODULE_NAME);
        this.asNumbersCB.setSelected(Configuration.LOGIC_VALUES_AS_NUMBER);
        this.strongConCB.setSelected(Configuration.KEEP_CONNECTED_ON_DRAG);
        
        this.lvalue0TF.setText(Configuration.LOGIC_0_VOLTAGE.toString());
        this.lvalue1TF.setText(Configuration.LOGIC_1_VOLTAGE.toString());
        
        this.modulesDirectoryTF.setText(mods.getAbsolutePath());
        this.modulesMetaDirectoryTF.setText(metas.getAbsolutePath());
        
        this.parent = parent;
    }
    
    public String indexToTheme(int index) {
        if (index == 0)
            return "themes/default.xml";
        else if (index == 1)
            return "themes/dark.xml";
        else if (index == 2)
            return "themes/vs.xml";
        else if (index == 3)
            return "themes/eclipse.xml";
        else if (index == 4)
            return "themes/idea.xml";
        return "";
    }
    
    public void applyChanges(final boolean closeAfter) {
        boolean needsReload = false;
        if (!modulesDirectoryTF.getText().equals(Configuration.MODULES_DIRECTORY_PATH)) {
            Configuration.MODULES_DIRECTORY_PATH = modulesDirectoryTF.getText();
            needsReload = true;
        }
        
        if (!modulesMetaDirectoryTF.getText().equals(Configuration.MODULE_METADATA_DIRECTORY_PATH)) {
            Configuration.MODULE_METADATA_DIRECTORY_PATH = modulesMetaDirectoryTF.getText();
            needsReload = true;
        }
        
        if (needsReload) {
            Loader.getInstance().loadModules();
            parent.needsRefresh = true;
        }
        
        Configuration.USE_CUSTOM_MODULE_NAME = shModName.isSelected();
        Configuration.COMPILE_ON_SAVE = compileOnSaveCB.isSelected();
        Configuration.DEBUG_MODE = debugModeCB.isSelected();
        Configuration.LOGIC_VALUES_AS_NUMBER = asNumbersCB.isSelected();
        Configuration.SMALL_GRID = true;
        
        Configuration.LOGIC_0_VOLTAGE = Double.parseDouble(lvalue0TF.getText());
        Configuration.LOGIC_1_VOLTAGE = Double.parseDouble(lvalue1TF.getText());
        Configuration.REPAINT_PAUSE = 10;
        
        Configuration.KEEP_CONNECTED_ON_DRAG = strongConCB.isSelected();
        
        Configuration.saveToFile(Configuration.CONFIG_FILE_NAME);
        Configuration.THEME = indexToTheme(themeCB.getSelectedIndex());
        
        JInternalFrame[] frames = this.getDesktopPane().getAllFrames();
        for (JInternalFrame jInternalFrame : frames) {
            if (jInternalFrame instanceof DesignWindow) {
                ((DesignWindow)jInternalFrame).refreshTheme();
            }
        }
        
        status.setText("Settings successfully saved.");
        status.setForeground(Color.GREEN.darker());
        
        int delay = 5000; 
        ActionListener taskPerformer = new ActionListener() {
            boolean close = closeAfter;
            @Override
            public void actionPerformed(ActionEvent evt) {
                status.setText("");
                if (close)
                    setVisible(false);
            }
        };
        Timer timer = new Timer(delay, taskPerformer);
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modulesDirectoryTF = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        modulesMetaDirectoryTF = new javax.swing.JTextField();
        browseButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        compileOnSaveCB = new javax.swing.JCheckBox();
        debugModeCB = new javax.swing.JCheckBox();
        asNumbersCB = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        lvalue1TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lvalue0TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        strongConCB = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        themeCB = new javax.swing.JComboBox();
        shModName = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        status = new javax.swing.JLabel();
        applyBtn = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Settings Editor");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Module storage directory");

        browseButton.setText("...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Module metadata storage directory");

        browseButton1.setText("...");
        browseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButton1ActionPerformed(evt);
            }
        });

        compileOnSaveCB.setText("Compile on save");

        debugModeCB.setText("Developer Mode");

        asNumbersCB.setText("Show logic values as numbers");

        lvalue1TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lvalue1TF.setText("0");

        jLabel3.setText("Logic value 1 voltage:");

        lvalue0TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("Logic value 0 voltage:");

        strongConCB.setText("Keep elements connected on drag");

        jLabel7.setText("Text Editor Theme");

        themeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Dark", "Visual Studio", "Eclipse", "Idea" }));

        shModName.setText("Show Custom Module Name ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(modulesMetaDirectoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(browseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(modulesDirectoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(compileOnSaveCB)
                                            .addComponent(debugModeCB))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(strongConCB)
                                                .addGap(23, 23, 23)
                                                .addComponent(asNumbersCB))
                                            .addComponent(shModName))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lvalue1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lvalue0TF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(themeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(modulesDirectoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(modulesMetaDirectoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compileOnSaveCB)
                    .addComponent(asNumbersCB)
                    .addComponent(strongConCB))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debugModeCB)
                    .addComponent(shModName))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvalue1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lvalue0TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(themeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("General Settings", jPanel1);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        applyBtn.setText("Apply");
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(applyBtn)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveButton)
                        .addComponent(applyBtn))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        setVisible(false);
    }//GEN-LAST:event_formInternalFrameClosing

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        applyChanges(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        applyChanges(false);
    }//GEN-LAST:event_applyBtnActionPerformed

    private void browseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser(Configuration.MODULE_METADATA_DIRECTORY_PATH);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int choose = fileChooser.showOpenDialog(this);
        if (choose != JFileChooser.APPROVE_OPTION)
        return;
        File target = fileChooser.getSelectedFile();
        modulesMetaDirectoryTF.setText(target.getAbsolutePath());
    }//GEN-LAST:event_browseButton1ActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser(Configuration.MODULES_DIRECTORY_PATH);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int choose = fileChooser.showOpenDialog(this);
        if (choose != JFileChooser.APPROVE_OPTION)
        return;
        File target = fileChooser.getSelectedFile();
        modulesDirectoryTF.setText(target.getAbsolutePath());
    }//GEN-LAST:event_browseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyBtn;
    private javax.swing.JCheckBox asNumbersCB;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton browseButton1;
    private javax.swing.JCheckBox compileOnSaveCB;
    private javax.swing.JCheckBox debugModeCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField lvalue0TF;
    private javax.swing.JTextField lvalue1TF;
    private javax.swing.JTextField modulesDirectoryTF;
    private javax.swing.JTextField modulesMetaDirectoryTF;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox shModName;
    private javax.swing.JLabel status;
    private javax.swing.JCheckBox strongConCB;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JComboBox themeCB;
    // End of variables declaration//GEN-END:variables
}
