/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Simulation;

import DataStructures.ModuleInfo;
import DataStructures.ModuleRepository;
import GUI.Design.VerilogPanel;

/**
 *
 * @author Néstor A. Bermúdez < nestor.bermudezs@gmail.com >
 */
public class DrilldownWindow extends javax.swing.JInternalFrame {
    ModuleInfo moduleInfo;
    DrilldownPanel canvas;
    VerilogPanel program;
    /**
     * Creates new form DrilldownPanel
     */
    public DrilldownWindow(ModuleInfo moduleInfo) {
        super("Module: " + moduleInfo.getModuleName(), true, true, true, true);
        this.moduleInfo = moduleInfo;
        initComponents();
        
        if (moduleInfo.isLeaf()) {
            program = new VerilogPanel();
            this.add(program);
            
            program.setProgram(moduleInfo.getSource());
            program.setVisible(true);            
        } else {
            canvas = new DrilldownPanel(moduleInfo);
            setContentPane(canvas);
        }
        pack();
        setVisible(true);
    }
    
    public DrilldownWindow(String moduleName) {
        super("Module: " + moduleName, true, true, true, true);
        this.moduleInfo = ModuleRepository.getInstance().getModuleInfo(moduleName);
        initComponents();
        
        if (moduleInfo.isLeaf()) {
            program = new VerilogPanel();
            program.setProgram(moduleInfo.getSource());
            program.setVisible(true);
            program.setReadOnly(true);
            setContentPane(program);
        } else {
            canvas = new DrilldownPanel(moduleInfo);
            setContentPane(canvas);
        }
        pack();
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
