package VerilogCompiler;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 14 23:47:20 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int R_ARIT_SHIFT = 19;
  public static final int KW_ALWAYS = 28;
  public static final int KW_NEGEDGE = 49;
  public static final int BIT_NAND = 8;
  public static final int KW_INTEGER = 45;
  public static final int IDENTIFIER = 2;
  public static final int REL_NOTEQ = 12;
  public static final int KW_EDGE = 35;
  public static final int REL_LST = 14;
  public static final int KW_NOR = 50;
  public static final int KW_DEASSIGN = 33;
  public static final int KW_INITIAL = 43;
  public static final int OP_MOD = 25;
  public static final int OP_MINUS = 21;
  public static final int KW_CASE = 32;
  public static final int KW_BEGIN = 31;
  public static final int REL_EQ = 11;
  public static final int KW_SUPPLY1 = 59;
  public static final int KW_SUPPLY0 = 58;
  public static final int COMMA = 83;
  public static final int BIT_AND = 3;
  public static final int KW_WAIT = 63;
  public static final int BIT_NEG = 27;
  public static final int KW_NAND = 48;
  public static final int BIT_XOR = 4;
  public static final int UNSIGNED_NUMBER = 78;
  public static final int OP_ADD = 22;
  public static final int OP_DIV = 24;
  public static final int DECIMAL_BASE = 74;
  public static final int KW_ASSIGN = 30;
  public static final int R_BRACKET = 71;
  public static final int R_SHIFT = 17;
  public static final int KW_FOR = 40;
  public static final int L_PARENTHESIS = 72;
  public static final int REL_GRT = 13;
  public static final int R_CURLY = 69;
  public static final int KW_MODULE = 47;
  public static final int REL_GRTEQ = 15;
  public static final int L_SHIFT = 18;
  public static final int KW_DEFAULT = 34;
  public static final int OP_TIMES = 23;
  public static final int SHARP = 84;
  public static final int KW_WAND = 60;
  public static final int L_BRACKET = 70;
  public static final int AT_SIGN = 80;
  public static final int REL_LSTEQ = 16;
  public static final int L_CURLY = 68;
  public static final int L_ARIT_SHIFT = 20;
  public static final int BIT_NOR = 7;
  public static final int LOG_OR = 10;
  public static final int BIT_OR = 6;
  public static final int KW_WIRE = 65;
  public static final int KW_END = 37;
  public static final int KW_REPEAT = 56;
  public static final int KW_FOREVER = 41;
  public static final int OCTAL_BASE = 75;
  public static final int KW_REG = 55;
  public static final int KW_OUTPUT = 51;
  public static final int BIT_XNOR = 5;
  public static final int SEMICOLON = 82;
  public static final int EOF = 0;
  public static final int KW_ENDMODULE = 39;
  public static final int KW_AND = 29;
  public static final int KW_ENDCASE = 38;
  public static final int KW_XOR = 67;
  public static final int BINARY_BASE = 76;
  public static final int error = 1;
  public static final int KW_WHILE = 64;
  public static final int KW_WOR = 61;
  public static final int KW_INPUT = 46;
  public static final int COLON = 81;
  public static final int LOG_AND = 9;
  public static final int KW_INOUT = 44;
  public static final int R_PARENTHESIS = 73;
  public static final int KW_ELSE = 36;
  public static final int KW_XNOR = 66;
  public static final int LOG_NEG = 26;
  public static final int KW_PARAMETER = 53;
  public static final int KW_SIGNED = 57;
  public static final int KW_OR = 52;
  public static final int STRING = 86;
  public static final int QUESTION_MARK = 79;
  public static final int HEX_BASE = 77;
  public static final int KW_POSEDGE = 54;
  public static final int KW_IF = 42;
  public static final int KW_UNSIGNED = 62;
  public static final int EQUALS = 85;
}

