
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 02 16:19:08 CST 2014
//----------------------------------------------------

package VerilogCompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int R_ARIT_SHIFT = 20;
  public static final int KW_ALWAYS = 29;
  public static final int KW_NEGEDGE = 50;
  public static final int BIT_NAND = 9;
  public static final int KW_INTEGER = 46;
  public static final int IDENTIFIER = 2;
  public static final int REL_NOTEQ = 13;
  public static final int KW_EDGE = 36;
  public static final int REL_LST = 15;
  public static final int KW_NOR = 51;
  public static final int KW_DEASSIGN = 34;
  public static final int KW_INITIAL = 44;
  public static final int OP_MOD = 26;
  public static final int OP_MINUS = 22;
  public static final int KW_CASE = 33;
  public static final int KW_BEGIN = 32;
  public static final int REL_EQ = 12;
  public static final int KW_SUPPLY1 = 60;
  public static final int KW_SUPPLY0 = 59;
  public static final int COMMA = 84;
  public static final int BIT_AND = 4;
  public static final int KW_WAIT = 64;
  public static final int BIT_NEG = 28;
  public static final int KW_NAND = 49;
  public static final int BIT_XOR = 5;
  public static final int UNSIGNED_NUMBER = 79;
  public static final int OP_ADD = 23;
  public static final int OP_DIV = 25;
  public static final int DECIMAL_BASE = 75;
  public static final int KW_ASSIGN = 31;
  public static final int R_BRACKET = 72;
  public static final int R_SHIFT = 18;
  public static final int KW_FOR = 41;
  public static final int L_PARENTHESIS = 73;
  public static final int REL_GRT = 14;
  public static final int R_CURLY = 70;
  public static final int KW_MODULE = 48;
  public static final int REL_GRTEQ = 16;
  public static final int L_SHIFT = 19;
  public static final int KW_DEFAULT = 35;
  public static final int OP_TIMES = 24;
  public static final int SHARP = 85;
  public static final int KW_WAND = 61;
  public static final int L_BRACKET = 71;
  public static final int AT_SIGN = 81;
  public static final int REL_LSTEQ = 17;
  public static final int L_CURLY = 69;
  public static final int L_ARIT_SHIFT = 21;
  public static final int BIT_NOR = 8;
  public static final int LOG_OR = 11;
  public static final int BIT_OR = 7;
  public static final int KW_WIRE = 66;
  public static final int KW_END = 38;
  public static final int KW_REPEAT = 57;
  public static final int KW_FOREVER = 42;
  public static final int OCTAL_BASE = 76;
  public static final int KW_REG = 56;
  public static final int KW_OUTPUT = 52;
  public static final int BIT_XNOR = 6;
  public static final int SEMICOLON = 83;
  public static final int EOF = 0;
  public static final int KW_ENDMODULE = 40;
  public static final int KW_AND = 30;
  public static final int KW_ENDCASE = 39;
  public static final int KW_XOR = 68;
  public static final int BINARY_BASE = 77;
  public static final int error = 1;
  public static final int KW_WHILE = 65;
  public static final int KW_WOR = 62;
  public static final int KW_INPUT = 47;
  public static final int COLON = 82;
  public static final int LOG_AND = 10;
  public static final int KW_INOUT = 45;
  public static final int R_PARENTHESIS = 74;
  public static final int KW_ELSE = 37;
  public static final int KW_XNOR = 67;
  public static final int LOG_NEG = 27;
  public static final int KW_PARAMETER = 54;
  public static final int KW_SIGNED = 58;
  public static final int KW_OR = 53;
  public static final int STRING = 87;
  public static final int QUESTION_MARK = 80;
  public static final int HEX_BASE = 78;
  public static final int KW_POSEDGE = 55;
  public static final int KW_IF = 43;
  public static final int HEX_NUMBER = 3;
  public static final int KW_UNSIGNED = 63;
  public static final int EQUALS = 86;
}

