/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Watcher.Selector;

import GUI.MainWindow;
import GUI.Watcher.Watches;
import GUI.Watcher.WatchesTableModel;
import VerilogCompiler.Interpretation.InstanceModuleScope;
import VerilogCompiler.Interpretation.SimulationScope;
import java.util.Set;

/**
 *
 * @author Néstor A. Bermúdez < nestor.bermudezs@gmail.com >
 */
public class WatchesSelector extends javax.swing.JDialog {

    SimulationScope scope;
    String moduleInstanceId;
    WatchesTableModel watches;
    Watches watcherWindow;
    MainWindow realParent;
    
    /**
     * Creates new form WatchesSelector
     */
    public WatchesSelector(MainWindow realParent, Watches watcherWindow,
            WatchesTableModel watches, SimulationScope simulationScope, 
            String moduleInstanceId, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.scope = simulationScope;
        this.moduleInstanceId = moduleInstanceId;
        this.watches = watches;
        this.realParent = realParent;
        this.watcherWindow = watcherWindow;
        
        InstanceModuleScope modScope = simulationScope.getScope(moduleInstanceId);
        Set<String> names = modScope.getVariableNames();
        variables.setModel(WatchesSelectorTableModel.fromVariableSet(watches, names, moduleInstanceId));
        
        variables.getColumn("").setMaxWidth(30);
        
        setLocation((realParent.getWidth() - getWidth()) / 2, 
                (realParent.getHeight() - getHeight()) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        variables = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        variables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", "Variable Name"
            }
        ));
        variables.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(variables);
        variables.getColumnModel().getColumn(0).setResizable(false);
        variables.getColumnModel().getColumn(0).setPreferredWidth(35);

        addBtn.setText("Add Watches");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        WatchesSelectorTableModel model = (WatchesSelectorTableModel) variables.getModel();
        for (WatchesSelectorModelEntry entry : model.data) {
            if (entry.beingWatched)
                watches.addWatch(entry.variableName, moduleInstanceId);
            else 
                watches.removeWatch(entry.variableName, moduleInstanceId);
        }
        watcherWindow.setLocation(realParent.getWidth() - watcherWindow.getWidth() - 17,
                watcherWindow.getY());
        watcherWindow.setVisible(true);
        realParent.addWatcherWindow(watcherWindow);
        this.dispose();
    }//GEN-LAST:event_addBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable variables;
    // End of variables declaration//GEN-END:variables
}
